apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: postgresql:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password:  ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500  # PostgreSQL 15 버전 기준
      timescaledb: false
    editable: true
